# Generated by Django 5.0.6 on 2024-10-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
